server = "https://{}.thoughtspotdev.cloud"
git_directory = "/Users/{}/thoughtspot_tml/dev"
releases_directory = "/Users/{}/thoughtspot_tml/releases"
parent_child_guid_map_file = "/Users/{}/thoughtspot_tml/guids/guids_map.json"
username = ""
password_do_not_enter_manually = ""

[environment_obj_name_prefixes]
dev = ""
test = ""
prod = ""

[connection_name_map]
"Original Connection 1" = "Destination Connection 1"
"Snowflake Dev" = "Snowflake - Prod"
