env_name = "test"
server = "https://{}.thoughtspotdev.cloud"
username = ""
cred_set_automatically = ""
cred_type = "t"

[table_properties_map]
"Dev Snowflake.NEWRETAIL.RETAIL" = "Bryant Snowflake Test.RETAIL.PUBLIC"
"Dev Snowflake.SALES.PUBLIC" = "Bryant Snowflake Test.SALES.PUBLIC"
"Dev Snowflake.DATA_CHALLENGE.PUBLIC" = "Bryant Snowflake Test.DATA_CHALLENGE.PUBLIC"

[object_prefix_changes]
previous_env_prefix = "dev_"
new_env_prefix = "test_"

[sharing_groups_read_only]
table = ['group_1', 'test_viewers']
view = []
worksheet = []
answer = []
liveboard = []

[sharing_groups_edit]
table = ['data_devs', 'semi_admins']
view = []
worksheet = []
answer = []
liveboard = []
