git_directory = "/Users/{}/thoughtspot_tml/dev"
releases_directory = "/Users/{}/thoughtspot_tml/releases"
parent_child_guid_map_file = "/Users/{}/thoughtspot_tml/guids/guids_map.json"
server = "https://{}.thoughtspotdev.cloud"
username = ""
cred_set_automatically = ""
cred_type = "t"

[environment_config_files]
test = "test_config.toml"
prod = "prod_config.toml"

[table_properties_map]

[object_prefix_changes]
previous_env_prefix = ""
new_env_prefix = ""

[sharing_groups_read_only]
table = []
view = []
worksheet = []
answer = []
liveboard = []

[sharing_groups_edit]
table = []
view = []
worksheet = []
answer = []
liveboard = []
